### ISSUE TITLE
Node thrift returning byte array

### ISSUE THREAD

**Issue by seleregb** [bancek/node-thrift-utf8#1]
Hello,

This is not an issue with your node module, I just didn't know how to reach you.

I am having an issue with node thrift returning a byte array and I want to convert it back to UTF8 with no such luck. I stumbled on your package but don't know how I implement it. 

This is my current code for scanning through a hbase table using the node "hbase" package:

<pre><code>
var hbase = require('hbase');

var client = hbase({
  host: '127.0.0.1',
  port: 8080
});

client
.table('Date-Of-Repairs')
.scan({
  startRow: '01/01/2009',
  maxVersions: 1
}, function(err, rows){
  console.log(err, ab2str(rows));
});

function ab2str(buf) {
   var str = "";
   var ab = new Uint16Array(buf);
   var abLen = ab.length;
   var CHUNK_SIZE = Math.pow(2, 16);
   var offset, len, subab;
   for (offset = 0; offset < abLen; offset += CHUNK_SIZE) {
      len = Math.min(CHUNK_SIZE, abLen-offset);
      subab = ab.subarray(offset, offset+len);
      str += String.fromCharCode.apply(null, subab);
   }
   return str;
}
</pre></code>

The abstr function I found online but that only returns "/uuuu/uuuu/uuuu". How can I use your package to solve my problem?

**Comment by bancek** [comment]
`hbase` library that you're using uses HBase's REST API (not Thrift).

Take a look at https://github.com/wdavidw/node-hbase/blob/master/src/scanner.coffee.md#scannergetcallback

**Comment by seleregb** [comment]
Yes i know it uses the rest api. I want to know how to use your module to convert the byte arrays I get in my console to UTF8.

**Comment by bancek** [comment]
My library is just a fix for thrift's UTF-8 bug. You cannot use it any other way.

Take a look at this: https://github.com/wdavidw/node-hbase/blob/master/test/scanner.coffee#L57 and https://nodejs.org/api/buffer.html

You should be able to access column data using column property: `rows[0].column`
